apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: pipeline-patch.yaml
- path: secrets-patch.yaml

configMapGenerator:
- name: instructlab-pipeline-params
  behavior: merge
  literals:
  - k8s_storage_class_name=gp3-csi
  - train_gpu_identifier=nvidia.com/gpu
  - sdg_batch_size=16
  - sdg_num_workers=4
  - train_num_workers=2
  - train_memory_per_worker=120Gi
